import logging
from typing import Dict, Any, List
from langchain.agents import AgentType, initialize_agent
from langchain_community.utilities.jira import JiraAPIWrapper
from langchain_community.agent_toolkits.jira.toolkit import JiraToolkit
from langchain_google_genai import ChatGoogleGenerativeAI
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type
import requests # Import requests to catch HTTPError
import google.api_core.exceptions # Import for ResourceExhausted specific exceptions

logger = logging.getLogger(__name__)

class JiraAgent:
    """
    Agent specialized in handling Jira ticket operations and project management.
    This class combines the agent logic and the underlying tool execution.
    """

    def __init__(self, llm: ChatGoogleGenerativeAI):
        self.llm = llm
        self.jira_wrapper = None
        self.jira_executor = None
        # Initialize the agent and check if it's enabled based on the success of initialization
        self.is_enabled = self._initialize_agent()

    def _initialize_agent(self) -> bool:
        """
        Initializes the Jira API wrapper and the LangChain agent executor.
        Returns True if initialization is successful, False otherwise.
        """
        try:
            # Initialize the Jira API wrapper which handles credentials automatically
            # This requires JIRA_INSTANCE_URL, JIRA_EMAIL, JIRA_API_TOKEN environment variables to be set.
            self.jira_wrapper = JiraAPIWrapper()

            # Create a toolkit that provides a list of pre-defined Jira tools
            jira_toolkit = JiraToolkit.from_jira_api_wrapper(self.jira_wrapper)
            tools = jira_toolkit.get_tools()

            # Use the initialize_agent function for a robust, pre-configured agent.
            # AgentType.ZERO_SHOT_REACT_DESCRIPTION uses tool descriptions to reason
            # about which tool to use, making it generally stable.
            # handle_parsing_errors=True allows the agent to recover from LLM output parsing issues.
            self.jira_executor = initialize_agent(
                tools,
                self.llm,
                agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
                handle_parsing_errors=True,
                verbose=True # Set to True for detailed logs of agent's thought process
            )

            logger.info("✅ Jira Agent initialized successfully using initialize_agent.")
            return True

        except Exception as e:
            # Log any exceptions that occur during agent initialization
            logger.error(f"❌ Failed to initialize Jira Agent: {e}", exc_info=True)
            return False

    @retry(
        # Stop after 5 attempts to prevent infinite retries
        stop=stop_after_attempt(5),
        # Wait exponentially between retries: 1 * (2**n) seconds, with min 4s and max 10s
        wait=wait_exponential(multiplier=1, min=4, max=10),
        # Only retry if the exception is a Google API ResourceExhausted error (429)
        retry=retry_if_exception_type(google.api_core.exceptions.ResourceExhausted),
        # Re-raise the last exception if all retries fail
        reraise=True
    )
    def process_query(self, question: str) -> str:
        """
        Processes a query by invoking the Jira agent executor.
        This method includes retry logic for transient errors like ResourceExhausted.

        Args:
            question: The user's question or command for Jira.

        Returns:
            The result from the Jira agent, or an error message if processing fails.
        """
        # Check if the Jira agent was successfully initialized
        if not self.is_enabled:
            return (
                "Jira integration is not configured. Please ensure the following environment "
                "variables are set: JIRA_INSTANCE_URL, JIRA_EMAIL, JIRA_API_TOKEN."
            )
        try:
            logger.info(f"Processing Jira query: '{question}'")
            # Invoke the agent executor with the user's question
            result = self.jira_executor.invoke({"input": question})
            # Return the output from the agent, or a default message if no output is found
            return result.get('output', 'No output from Jira agent.')
        except requests.exceptions.HTTPError as http_e:
            # Catch specific HTTP errors, which often indicate issues with the Jira API call
            # or the JQL query generated by the LLM. These are typically not transient errors.
            error_message = str(http_e)
            if "JQL Query" in error_message and "quoted string" in error_message:
                # This specific error indicates a malformed JQL query from the LLM
                logger.error(f"Error processing Jira query due to JQL syntax: {error_message}", exc_info=True)
                return (
                    f"Sorry, I encountered an error with the Jira query due to a syntax issue. "
                    f"The query generated was malformed. Please try rephrasing your request more clearly, "
                    f"for example, by specifying exact dates (e.g., 'yesterday', '2023-10-27') "
                    f"or avoiding ambiguous phrases that might lead to incomplete JQL. "
                    f"Details: {error_message}"
                )
            else:
                # Handle other types of HTTP errors
                logger.error(f"Error processing Jira query: {http_e}", exc_info=True)
                return f"Sorry, I encountered an HTTP error while processing your Jira request: {http_e}"
        except Exception as e:
            # Catch any other unexpected errors that are not `ResourceExhausted` or `HTTPError`.
            # If `tenacity` didn't catch `ResourceExhausted` and retry, it will propagate here.
            logger.error(f"An unexpected error occurred while processing Jira query: {e}", exc_info=True)
            # Re-raise the exception to allow the `@retry` decorator to catch it if it's a
            # `ResourceExhausted` error, or to propagate it if it's another unhandled exception.
            raise e
    
    def get_integration_status(self) -> Dict[str, Any]:
        """
        Get status information about the Jira integration.
        
        Returns:
            Dictionary with integration status information
        """
        return {
            "integration_name": "Jira",
            "enabled": self.is_enabled,
            "status": "active" if self.is_enabled else "disabled",
            "error": None if self.is_enabled else "Jira integration not configured"
        }
